### ISSUE TITLE
Подразумевается ли, что в систему нужно логиниться?

### ISSUE THREAD

**Issue by krsnv** [katyfrolova/elama-test-app#3]
https://github.com/katyfrolova/elama-test-app/blob/a27d0caaff5c99c2a89f48583a36273bf212d531/test_app/app.py#L44

**Comment by katerina-f** [comment]
я думаю сделать дополнительную модель Employees для сотрудников, то есть Юзер будет логиниться, как сейчас логинится например в приложении для HR, а сотрудник будет заполняться из формы - опять же, как он сейчас делает. Мы же будем отправлять Юзеру сообщения о сотрудниках - будут разные модели с разными полями. Это я сейчас переделаю
