### ISSUE TITLE
Можно ли сделать статическим?

### ISSUE THREAD

**Issue by krsnv** [katyfrolova/elama-test-app#8]
https://github.com/katyfrolova/elama-test-app/blob/a27d0caaff5c99c2a89f48583a36273bf212d531/test_app/reminder/reminder.py#L42

**Comment by katerina-f** [comment]
Ты имеешь ввиду сделать сообщение статическим а данные в него подавать из модели? Я думаю да, поэтому не стала пока его писать

**Comment by katerina-f** [comment]
убрала вообще этот метод за ненадобностью
